#!/usr/local/php5/bin/php
<?php

// Remember to set the path to your thllibrary!
$db = new SQlite3('/Users/yourUser/Documents/gtd.thllibrary/library.sqlite3');

$dueToday = 
	'SELECT ZTITLE, ZNOTES
	FROM ZTASK
	WHERE date(ZDUEDATE,"UNIXEPOCH","+31 YEARS")= date("now","localtime")
	AND ZCOMPLETEDDATE IS NULL
	AND ZCANCELEDDATE IS NULL
	ORDER BY ZSTARTDATE DESC';

$startToday = 
	'SELECT ZTITLE,ZDUEDATE
	FROM ZTASK
	WHERE date(ZDUEDATE,"UNIXEPOCH","+31 YEARS")>date("now","localtime")
	AND date(ZDUEDATE,"UNIXEPOCH","+31 YEARS")<=date("now","localtime","+3 DAYS")
	AND ZCOMPLETEDDATE IS NULL
	AND ZCANCELEDDATE IS NULL
	ORDER BY ZSTARTDATE DESC';

$cuales = $argv[1];
if($cuales == 'tudei'){
	$poo = $db->query($dueToday);
} else {
	$poo = $db->query($startToday);
}


while($i = $poo->fetchArray(SQLITE3_ASSOC)){
	$hasResults = true;
	$date = $cuales=='tudei'? '' : date('m/d',$i['ZDUEDATE']).' -> ';
	$titulo = $i['ZTITLE'];
	$tags = array();
	preg_match_all('/\s\/(\w+)/', $titulo,$tags);
	$tags = count($tags>0)? ' ['.preg_replace('/\s\//', '', implode('/',$tags[0])).']' : '';
	$poop .= '» '.$date.strtoupper(preg_replace('/\s\/(\w+)/', '', $titulo)).$tags."\n";
}

if(!isset($hasResults)){
	echo '» All done!
   Now go out and play :)';
	die();
}

echo $poop;


?>